"""Oracle Stage-2 schedule provider — fixture and live modes (PM-1263 → PM-1269).

Fixture and live modes are explicitly separate. There is NEVER a silent
fixture fallback after a live retrieval failure (PM-1263 §3.7 / §5): a live
transport/parse failure raises ScheduleRetrievalError; an empty but
well-formed live response is a legitimate no-games day.

All network access is confined to fetch_live_schedule(). The normalizer
(normalize_response / normalize_game) is pure and operates on an
already-decoded payload, so it is fully offline-testable with controlled
inputs.

retrieved_at is generated by THIS provider at fetch time and is never taken
from MLB response content or supplied/overridden by a downstream caller
(PM-1269 §3.2). It is a LOCAL observation-order signal only; it is not a
claim of freshness inside the provider's system.

The scheduled start is each game's own gameDate (full UTC), not the slate
date (PM-1263 §2.4). The slate date is only the query/grouping key.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import date, datetime, timezone

import requests

from backend.oracle import underlying_identity as ui
from backend.oracle.fixtures import load_phase1_fixtures, validate_fixture_record

MODE_FIXTURE = "fixture"
MODE_LIVE = "live"

_STATSAPI_SCHEDULE_URL = "https://statsapi.mlb.com/api/v1/schedule"
_SPORT_ID = ui.SPORT_ID_MLB
_LIVE_TIMEOUT_SECONDS = 10

# Normalized eligible status; only the pregame-eligible family may be admitted.
STATUS_SCHEDULED = "scheduled"

# detailedState → eligibility (PM-1263 §3.4 / PM-1269). Unknown → INELIGIBLE
# (fail-closed): the opposite of fetchers/mlb_stats_api.STATUS_MAP's fail-open
# default, which must never be reused for admission.
_ELIGIBLE_STATES = frozenset({"Scheduled", "Pre-Game", "Warmup"})
_INELIGIBLE_STATES = frozenset({
    "In Progress", "Final", "Game Over", "Completed Early", "Postponed",
    "Cancelled", "Canceled", "Suspended", "Delayed", "Delayed Start",
    "Resumed",
})

# Disposition of an observed game within a snapshot.
DISPOSITION_ADMITTED = "admitted"
DISPOSITION_EXCLUDED = "excluded"

# Exclusion reasons (bounded).
REASON_MISSING_IDENTITY = "missing_identity"
REASON_MISSING_TEAMS = "missing_teams"
REASON_INVALID_START = "invalid_start"
REASON_TBD_START = "tbd_start"
REASON_UNKNOWN_STATUS = "unknown_status"
REASON_INELIGIBLE_STATUS = "ineligible_status"
REASON_CONFLICTING_DUPLICATE = "conflicting_duplicate"


class ScheduleRetrievalError(Exception):
    """Raised on a live transport/parse failure (fail-closed; PM-1263 §3.7).

    Distinct from an empty-but-well-formed response, which is a legitimate
    no-games day. Never triggers a fixture fallback.
    """


@dataclass(frozen=True)
class NormalizedGame:
    """One observed game normalized to the Stage-2 contract shape."""

    source_namespace: str
    sport_id: int
    game_pk: str
    away_team: str
    home_team: str
    scheduled_start_at: datetime          # timezone-aware UTC
    game_status: str                      # normalized (STATUS_SCHEDULED) for admitted
    source_game_date: str | None
    doubleheader: dict | None
    venue: str | None
    content_digest: str
    disposition: str
    reason: str | None = None

    def sui(self) -> tuple[str, int, str]:
        return (self.source_namespace, self.sport_id, self.game_pk)


@dataclass(frozen=True)
class ExcludedGame:
    """An observed game excluded from admission but retained as evidence."""

    source_namespace: str
    sport_id: int
    game_pk: str | None
    disposition: str
    reason: str
    detail: str | None = None


@dataclass(frozen=True)
class Snapshot:
    """A normalized Stage-2 schedule snapshot (PM-1265 §4 / PM-1269 §4)."""

    mode: str
    source: str
    requested_slate_date: str             # America/Toronto business date (ISO)
    retrieved_at: datetime                # provider-owned, timezone-aware UTC
    included: tuple[NormalizedGame, ...]  # admitted, deduped by SUI
    excluded: tuple[ExcludedGame, ...]    # evidence only
    empty: bool                           # well-formed response, no eligible games

    def source_namespace(self) -> str:
        return ui.SOURCE_NAMESPACE_FIXTURE if self.mode == MODE_FIXTURE else ui.SOURCE_NAMESPACE_MLB


def _parse_game_date(raw_game: dict) -> datetime | None:
    game_date = raw_game.get("gameDate")
    if not isinstance(game_date, str) or "T" not in game_date:
        return None
    try:
        dt = datetime.fromisoformat(game_date.replace("Z", "+00:00"))
    except ValueError:
        return None
    if dt.tzinfo is None:
        return None
    return dt.astimezone(timezone.utc)


def _extract_doubleheader(raw_game: dict) -> dict | None:
    dh = raw_game.get("doubleHeader")
    number = raw_game.get("gameNumber")
    if dh is None and number is None:
        return None
    return {"doubleHeader": dh, "gameNumber": number}


def normalize_game(
    raw_game: dict,
    requested_slate_date: str,
    source_namespace: str,
    source_game_date: str | None,
) -> NormalizedGame | ExcludedGame:
    """Normalize one raw MLB schedule game (pure; fail-closed on any ambiguity).

    source_game_date is the provider's dates[].date grouping value; the
    scheduled start is the game's own gameDate (UTC), never the slate date.
    """
    game_pk_raw = raw_game.get("gamePk")
    game_pk = str(game_pk_raw) if game_pk_raw is not None else None
    if game_pk is None or not game_pk.isdigit():
        return ExcludedGame(source_namespace, _SPORT_ID, None,
                            DISPOSITION_EXCLUDED, REASON_MISSING_IDENTITY,
                            detail=f"gamePk={game_pk_raw!r}")

    teams = raw_game.get("teams") or {}
    home = (((teams.get("home") or {}).get("team")) or {}).get("abbreviation")
    away = (((teams.get("away") or {}).get("team")) or {}).get("abbreviation")
    if not home or not away:
        return ExcludedGame(source_namespace, _SPORT_ID, game_pk,
                            DISPOSITION_EXCLUDED, REASON_MISSING_TEAMS)

    status_obj = raw_game.get("status") or {}
    detailed_state = status_obj.get("detailedState")

    # TBD start: explicit provider flag or an unparseable/absent start.
    if status_obj.get("startTimeTBD") is True:
        return ExcludedGame(source_namespace, _SPORT_ID, game_pk,
                            DISPOSITION_EXCLUDED, REASON_TBD_START)

    start_at = _parse_game_date(raw_game)
    if start_at is None:
        return ExcludedGame(source_namespace, _SPORT_ID, game_pk,
                            DISPOSITION_EXCLUDED, REASON_INVALID_START)

    if detailed_state not in _ELIGIBLE_STATES:
        if detailed_state in _INELIGIBLE_STATES:
            reason, detail = REASON_INELIGIBLE_STATUS, str(detailed_state)
        else:
            reason, detail = REASON_UNKNOWN_STATUS, str(detailed_state)
        return ExcludedGame(source_namespace, _SPORT_ID, game_pk,
                            DISPOSITION_EXCLUDED, reason, detail=detail)

    digest = ui.content_digest(
        source_namespace=source_namespace,
        sport_id=_SPORT_ID,
        game_pk=game_pk,
        away_team=away,
        home_team=home,
        scheduled_start_at=start_at,
        game_status=STATUS_SCHEDULED,
        source_game_date=source_game_date,
    )
    return NormalizedGame(
        source_namespace=source_namespace,
        sport_id=_SPORT_ID,
        game_pk=game_pk,
        away_team=away,
        home_team=home,
        scheduled_start_at=start_at,
        game_status=STATUS_SCHEDULED,
        source_game_date=source_game_date,
        doubleheader=_extract_doubleheader(raw_game),
        venue=(raw_game.get("venue") or {}).get("name"),
        content_digest=digest,
        disposition=DISPOSITION_ADMITTED,
    )


def _dedupe_by_sui(
    admitted: list[NormalizedGame],
) -> tuple[list[NormalizedGame], list[ExcludedGame]]:
    """Dedup admitted games by SUI (PM-1265 §3.3).

    Identical duplicate (same content_digest) → keep one. Conflicting
    duplicate (same SUI, differing digest) → exclude that SUI fail-closed.
    """
    by_sui: dict[tuple, list[NormalizedGame]] = {}
    order: list[tuple] = []
    for g in admitted:
        key = g.sui()
        if key not in by_sui:
            by_sui[key] = []
            order.append(key)
        by_sui[key].append(g)

    kept: list[NormalizedGame] = []
    conflicts: list[ExcludedGame] = []
    for key in order:
        group = by_sui[key]
        digests = {g.content_digest for g in group}
        if len(digests) == 1:
            kept.append(group[0])
        else:
            ns, sport, pk = key
            conflicts.append(ExcludedGame(ns, sport, pk, DISPOSITION_EXCLUDED,
                                          REASON_CONFLICTING_DUPLICATE,
                                          detail=f"{len(digests)} distinct digests"))
    return kept, conflicts


def normalize_response(
    data: dict,
    requested_slate_date: str,
    retrieved_at: datetime,
    *,
    mode: str,
    source: str,
) -> Snapshot:
    """Normalize a decoded MLB /schedule payload into a Snapshot (pure).

    A well-formed payload with no games yields empty=True (a legitimate
    no-games day) — NOT an error. Malformed structure raises
    ScheduleRetrievalError (fail-closed; the caller must not treat it as a
    no-games day).
    """
    if not ui.is_timezone_aware(retrieved_at):
        raise ScheduleRetrievalError("retrieved_at must be timezone-aware")
    source_namespace = ui.SOURCE_NAMESPACE_FIXTURE if mode == MODE_FIXTURE else ui.SOURCE_NAMESPACE_MLB

    dates = data.get("dates")
    if dates is None or not isinstance(dates, list):
        raise ScheduleRetrievalError("malformed schedule payload: 'dates' missing or not a list")

    admitted: list[NormalizedGame] = []
    excluded: list[ExcludedGame] = []
    observed = 0
    for date_entry in dates:
        if not isinstance(date_entry, dict):
            raise ScheduleRetrievalError("malformed schedule payload: date entry not an object")
        source_game_date = date_entry.get("date")
        games = date_entry.get("games") or []
        if not isinstance(games, list):
            raise ScheduleRetrievalError("malformed schedule payload: 'games' not a list")
        for raw_game in games:
            if not isinstance(raw_game, dict):
                raise ScheduleRetrievalError("malformed schedule payload: game not an object")
            observed += 1
            result = normalize_game(raw_game, requested_slate_date, source_namespace, source_game_date)
            if isinstance(result, NormalizedGame):
                admitted.append(result)
            else:
                excluded.append(result)

    kept, conflicts = _dedupe_by_sui(admitted)
    excluded.extend(conflicts)
    return Snapshot(
        mode=mode,
        source=source,
        requested_slate_date=requested_slate_date,
        retrieved_at=retrieved_at,
        included=tuple(kept),
        excluded=tuple(excluded),
        empty=(observed == 0),
    )


def fetch_live_schedule(
    requested_slate_date: str,
    *,
    timeout: int = _LIVE_TIMEOUT_SECONDS,
    session: object | None = None,
) -> tuple[dict, datetime]:
    """Confined live GET against MLB /schedule. Returns (decoded_json, retrieved_at).

    retrieved_at is captured HERE at fetch time (provider-owned). Any
    transport/HTTP/decode failure raises ScheduleRetrievalError (fail-closed;
    never a fixture fallback). Network happens outside any DB lock/transaction
    (PM-1269 §3.5); the caller persists inside the locked transaction.
    """
    getter = session.get if session is not None else requests.get
    params = {"sportId": _SPORT_ID, "date": requested_slate_date, "hydrate": "team"}
    retrieved_at = datetime.now(tz=timezone.utc)
    try:
        response = getter(_STATSAPI_SCHEDULE_URL, params=params, timeout=timeout)
        response.raise_for_status()
        data = response.json()
    except requests.exceptions.RequestException as exc:
        raise ScheduleRetrievalError(f"live schedule transport failure: {type(exc).__name__}") from exc
    except ValueError as exc:  # JSON decode
        raise ScheduleRetrievalError("live schedule response was not valid JSON") from exc
    if not isinstance(data, dict):
        raise ScheduleRetrievalError("live schedule response was not a JSON object")
    return data, retrieved_at


def _fixture_payload() -> dict:
    """Build a /schedule-shaped payload from the checked-in Phase-1 fixtures.

    Runs the fixtures through the SAME normalizer as live data (record shape
    is intentionally identical; fixtures.py docstring), under the fixture
    namespace. Kept available for deterministic testing (PM-1263 §5); it is
    never substituted for a failed live retrieval.
    """
    games = []
    for record in load_phase1_fixtures():
        validate_fixture_record(record)
        games.append({
            "gamePk": int(record["external_game_id"]),
            "gameDate": record["first_pitch_time"],
            "status": {"detailedState": "Scheduled"},
            "teams": {
                "home": {"team": {"abbreviation": record["home_team"]}},
                "away": {"team": {"abbreviation": record["away_team"]}},
            },
            "venue": {"name": record["venue"]},
        })
    return {"dates": [{"date": None, "games": games}]}


def retrieve(
    mode: str,
    requested_slate_date: str,
    *,
    session: object | None = None,
) -> Snapshot:
    """Retrieve and normalize a Stage-2 schedule snapshot for the given mode.

    mode=MODE_FIXTURE uses the deterministic checked-in fixtures (fixture
    namespace). mode=MODE_LIVE performs one confined GET (mlb-statsapi
    namespace). No silent fallback between modes.
    """
    if mode == MODE_FIXTURE:
        retrieved_at = datetime.now(tz=timezone.utc)
        return normalize_response(
            _fixture_payload(), requested_slate_date, retrieved_at,
            mode=MODE_FIXTURE, source="oracle-fixture-schedule",
        )
    if mode == MODE_LIVE:
        data, retrieved_at = fetch_live_schedule(requested_slate_date, session=session)
        return normalize_response(
            data, requested_slate_date, retrieved_at,
            mode=MODE_LIVE, source="mlb-statsapi-schedule",
        )
    raise ScheduleRetrievalError(f"unknown schedule mode {mode!r}")
